# Generated by Django 4.2.17 on 2024-12-31 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('std_id', models.IntegerField(primary_key=True, serialize=False)),
                ('std_name', models.CharField(max_length=10)),
                ('team', models.IntegerField()),
                ('satb', models.CharField(choices=[('S', 'S'), ('A', 'A'), ('T', 'T'), ('B', 'B')], max_length=1)),
                ('j_or_h', models.CharField(choices=[('J', 'Junior'), ('H', 'High')], max_length=1)),
                ('std_tag', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
    ]
