# Generated by Django 4.2.17 on 2025-01-13 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('is_student', 'Student'), ('is_volunteer', 'Volunteer'), ('is_cs', 'Course Selection'), ('is_admin', 'Admin')]},
        ),
    ]
