# Generated by Django 4.2.17 on 2025-01-01 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminSetting',
            fields=[
                ('setting_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('configuration', models.CharField(max_length=50)),
            ],
        ),
    ]
