# Generated by Django 4.2.17 on 2025-01-01 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel('Students', 'Student')
]   
