# Generated by Django 4.2.17 on 2025-01-02 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0002_alter_course_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_info',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
