# Generated by Django 4.2.17 on 2025-01-01 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0002_adminsetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('std_id', models.IntegerField(primary_key=True, serialize=False)),
                ('std_name', models.CharField(max_length=10)),
                ('team', models.IntegerField(choices=[(1, '第一小隊'), (2, '第二小隊'), (3, '第三小隊'), (4, '第四小隊'), (5, '第五小隊'), (6, '第六小隊'), (7, '第七小隊'), (8, '第八小隊')])),
                ('satb', models.CharField(choices=[('S', 'S'), ('A', 'A'), ('T', 'T'), ('B', 'B')], max_length=1)),
                ('j_or_h', models.CharField(choices=[('J', 'Junior'), ('H', 'High')], max_length=1)),
                ('std_tag', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Students',
        ),
    ]
