# Generated by Django 4.2.17 on 2025-05-28 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0003_alter_student_j_or_h_alter_student_satb'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='assigned',
            field=models.BooleanField(default=False),
        ),
    ]
