# Generated by Django 4.2.17 on 2025-01-03 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0004_alter_course_course_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='section_display',
            field=models.CharField(default='', max_length=30),
        ),
    ]
