# Generated by Django 4.2.17 on 2025-01-05 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0006_rename_section_course_section_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='selection',
            old_name='student_id',
            new_name='std_id',
        ),
        migrations.AddField(
            model_name='selection',
            name='section_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='django_app.section'),
            preserve_default=False,
        ),
    ]
