# Generated by Django 4.2.17 on 2025-01-07 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0008_student_form1_completed_student_form2_completed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Special_Course',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=255)),
                ('course_info', models.TextField(blank=True, max_length=255, null=True)),
                ('std_limit', models.IntegerField(default=99)),
                ('course_type', models.CharField(max_length=2)),
                ('section_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='django_app.section')),
            ],
        ),
    ]
