# Generated by Django 4.2.17 on 2025-01-07 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0009_special_course'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Special_Course',
            new_name='SpecialCourse',
        ),
    ]
