# Generated by Django 4.2.17 on 2025-01-07 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0010_rename_special_course_specialcourse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selection',
            name='course_id',
            field=models.CharField(max_length=50),
        ),
    ]
