# Generated by Django 4.2.17 on 2025-01-08 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0011_alter_selection_course_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='selection',
            name='form_type',
            field=models.CharField(default='J1', max_length=2),
            preserve_default=False,
        ),
    ]
