# Generated by Django 4.2.17 on 2025-01-08 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0012_selection_form_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selection',
            name='form_type',
            field=models.CharField(default='J1', max_length=2),
        ),
    ]
