# Generated by Django 4.2.17 on 2025-01-08 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0014_rename_section_id_selection_section_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_type', models.CharField(default='J1', max_length=2)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_app.course')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_app.section')),
                ('std', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_app.student')),
            ],
        ),
    ]
