version: '3.9'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: yourrootpassword
      MYSQL_DATABASE: test_db
      MYSQL_USER: test_user
      MYSQL_PASSWORD: testpassword
    ports:
      - "3307:3306"
    volumes:
      - dbdata:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

  web:
    build: .
    container_name: django_container
    # environment:
    #   DJANGO_SUPERUSER_USERNAME: admin
    #   DJANGO_SUPERUSER_EMAIL: wildiam356@gmail.com
    #   DJANGO_SUPERUSER_PASSWORD: HTCCcs2025
    command: >
      sh -c "
      python manage.py migrate &&
      gunicorn django_project.wsgi:application --bind 0.0.0.0:8000
      "
    volumes:
      - .:/app
    depends_on:
      mysql:
        condition: service_healthy

  nginx:
    image: nginx:latest
    container_name: nginx_container
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./staticfiles:/django_project/staticfiles
    depends_on:
      web:
        condition: service_started

volumes:
  dbdata: